server:
  port: 9090
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/trud_expert}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  freemarker:
    expose-request-attributes: true

