version: '3.7'

services:
  postgres:
    container_name: trud-expert-postgres
    image: postgres:12.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: trud_expert
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

networks:
    default:
      name: test-network
      driver: bridge