server:
  port: 8080
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/trud_expert}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
  freemarker:
    expose-request-attributes: true
  flyway:
    baseline-on-migrate: true

